import { Injectable } from '@angular/core';

@Injectable()
export class DistrictsModuleService {

  constructor() {}

  public districts = [
    "anaMaria",
    "argentina",
    "arquimedesNapolini",
    "boaVista",
    "brasilia",
    "catarinense",
    "ceara",
    "centro",
    "cidadeMineira",
    "colonial",
    "coloninhaZili",
    "comerciario",
    "conjuntoHabitacionalNovaEsperanca",
    "cristoRedentor",
    "cruzeiroDoSul",
    "dagostin",
    "distritoIndustrial",
    "estacaozinha",
    "fabioSilva",
    "imigrantes",
    "imperatriz",
    "jardimAngelica",
    "jardimMaristela",
    "jardimPaineiras",
    "jardimUniao",
    "laranjinha",
    "liberdade",
    "linhaAnta",
    "linhaBatista",
    "loteSeis",
    "mariaCeu",
    "metropol",
    "michel",
    "milanese",
    "minaBrasil",
    "minaDoMato",
    "minaUniao",
    "mineiraNova",
    "mineiraVelha",
    "monteCastelo",
    "morroEstevao",
    "nossaSenhoraDaSalete",
    "operariaNova",
    "paraiso",
    "pedroZanivan",
    "pinheirinho",
    "pioCorrea",
    "pocoUm",
    "primeiraLinha",
    "progresso",
    "promorarVilaVitoria",
    "prospera",
    "quartaLinha",
    "recantoVerde",
    "renascer",
    "rioMaina",
    "sangao",
    "santaAugusta",
    "santaBarbara",
    "santaCatarina",
    "santaLuzia",
    "santoAntonio",
    "santosDumont",
    "saoCristovao",
    "saoDefende",
    "saoFrancisco",
    "saoJoao",
    "saoLuiz",
    "saoMarcos",
    "saoSebastiao",
    "saoSimao",
    "universitario",
    "veraCruz",
    "verdinho",
    "vilaBelmiro",
    "vilaFloresta",
    "vilaFlorestaII",
    "vilaFrancesa",
    "vilaIsabel",
    "vilaMacarini",
    "vilaManaus",
    "vilaMiguel",
    "vilaNovaEsperanca",
    "vilaRica",
    "vilaSaoJose",
    "vilaVisconde",
    "vilaZuleima",
    "wosocris"
  ]
  

  public districtsName = [
    "Ana Maria",
    "Argentina",
    "Arquimedes Napolini",
    "Boa Vista",
    "Brasília",
    "Catarinense",
    "Ceará",
    "Centro",
    "Cidade Mineira",
    "Colonial",
    "Coloninha Zili",
    "Comerciário",
    "Conjunto H. Nova Esperança",
    "Cristo Redentor",
    "Cruzeiro Do Sul",
    "Dagostin",
    "Distrito Industrial",
    "Estaçãozinha",
    "Fábio Silva",
    "Imigrantes",
    "Imperatriz",
    "Jardim Angélica",
    "Jardim Maristela",
    "Jardim Paineiras",
    "Jardim União",
    "Laranjinha",
    "Liberdade",
    "Linha Anta",
    "Linha Batista",
    "Lote Seis",
    "Maria Céu",
    "Metropol",
    "Michel",
    "Milanese",
    "Mina Brasil",
    "Mina Do Mato",
    "Mina União",
    "Mineira Nova",
    "Mineira Velha",
    "Monte Castelo",
    "Morro Estêvão",
    "Nossa Senhora Da Salete",
    "Operária Nova",
    "Paraíso",
    "Pedro Zanivan",
    "Pinheirinho",
    "Pio Corrêa",
    "Poço Um",
    "Primeira Linha",
    "Progresso",
    "Promorar Vila Vitoria",
    "Próspera",
    "Quarta Linha",
    "Recanto Verde",
    "Renascer",
    "Rio Maina",
    "Sangão",
    "Santa Augusta",
    "Santa Bárbara",
    "Santa Catarina",
    "Santa Luzia",
    "Santo Antônio",
    "Santos Dumont",
    "São Cristóvão",
    "São Defende",
    "São Francisco",
    "São João",
    "São Luiz",
    "São Marcos",
    "São Sebastião",
    "São Simão",
    "Universitário",
    "Vera Cruz",
    "Verdinho",
    "Vila Belmiro",
    "Vila Floresta",
    "Vila Floresta II",
    "Vila Francesa",
    "Vila Isabel",
    "Vila Macarini",
    "Vila Manaus",
    "Vila Miguel",
    "Vila Nova Esperança",
    "Vila Rica",
    "Vila São José",
    "Vila Visconde",
    "Vila Zuleima",
    "Wosocris"
  ]

  getDistrict(index) {
  }

}
